### ISSUE TITLE
WfRunsListPersistentSearchHistory state is not being save properly 

### ISSUE THREAD

**Issue by Jonatha1983** [cunla/ghactions-manager#102]
**Describe the bug**
This class: WfRunsListPersistentSearchHistory 
is not being persisted because of an issue I found on my own plugin. 

You can see the Slack thread about it here:
https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1700212107064589

I wanted to open a PR with the simple fix - but this repo is close to external contribution so I ll just post the solution here: 

The Gradle dependency: 
```implementation(libs.serialization) ```
should be changed to:
```compileOnly(libs.serialization) ```

You can see in the logs when running a warning saying: 
```#c.i.u.x.Binding - no accessors for ... ````

and in fact, you will not find the WfRunsListSearchHistory element in the workspace.xml file under the .idea folder.

with this change, the state will persist properly.

**Comment by danielm-cfa** [comment]
Hi, thanks for this.

Generally speaking, you can fork and then create a PR from the fork.
But I will apply the change shortly.

**Comment by Jonatha1983** [comment]
I tried forking but got an unauthorized message.

**Comment by cunla** [comment]
I am not sure why you were unable to fork. Can you check again and send me details?
