### ISSUE TITLE
Check for action updates

### ISSUE THREAD

**Issue by LecrisUT** [cunla/ghactions-manager#105]
Some projects do not have dependabot setup because it can get quite noisy. It would be nice if IDE tools like this can check the actions for updates instead

**Comment by cunla** [comment]
Oh, I get you... I actually created a CLI for it: https://github.com/dsoftwareinc/github-actions-cli

I think it would be nice to have the editor mark an upgradable action in yellow - that's the usual behavior for pip, etc.
It fits more on https://github.com/YunaBraska/github-workflow-plugin. I will ask if they want to cooperate to include it.
