### ISSUE TITLE
Add global setting to filter workflows for current branch

### ISSUE THREAD

**Issue by Sam13** [cunla/ghactions-manager#115]
**Is your feature request related to a problem? Please describe.**
Add a global option to filter workflow runs to the current checkout branch.
This is useful when working with feature branches in a repo which has lots of workflow runs.

**Describe the solution you'd like**
Add a checkbox in the settings UI where you can enable filtering workflows for current branch 

**Describe alternatives you've considered**
Selecting the corresponding branch manually after you changed your checkout branch

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/115">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/115/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/115/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Hi,

I like the idea, I will add quick filters for current branch and current user.

I am not sure how to listen to a change branch event, I will see whether I find it.

**Comment by cunla** [comment]
done, I did significant refactoring, so I am going to test is locally for a week and then release a new version.
If you want to try out the unreleased version, let me know, I will send you the distribution.

**Comment by Sam13** [comment]
Thanks for the new feature.
Looking forward to next release 👍
