### ISSUE TITLE
Message "Log is too big to display, showing only first 1mb"

### ISSUE THREAD

**Issue by kriegaex** [cunla/ghactions-manager#118]
When opening https://github.com/eclipse-aspectj/aspectj/actions/runs/8175351748/job/22352264016 in the plugin, I see this:

```text
---- Step  13: Run Tests ----
Log is too big to display, showing only first 1mb---- Step  24: Post Set up cache for ~./m2/repository ----
2024-03-06T16:40:04.3007481Z Post job cleanup.
2024-03-06T16:40:04.4173507Z Cache hit occurred on the primary key maven-Linux-java-17-fce8bec3cd42e16693cef9a43c714ae29bef30ad350d18a0989733b31da37d1e, not saving cache.
---- Step  25: Post Set up JDK 17 ----
2024-03-06T16:40:04.4292243Z Post job cleanup.
```

![image](https://github.com/cunla/ghactions-manager/assets/1537384/bf98f704-2ea0-4896-bdac-d4b295203ac7)

Is there any way in the API to load the actual log? It can be optional for efficiency, but the user should at least have the option to load it.

On GitHub, it looks like this:

![image](https://github.com/cunla/ghactions-manager/assets/1537384/2584721c-4119-4353-8005-d395b3e8a5d4)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/118">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/118/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/118/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
This is by design. 

GitHub API provides the logs regardless of size (though it might affect speed).

JetBrains IDE ConsoleView is limited to 1mb text (So it would not take more RAM than it already does :) )

**Comment by kriegaex** [comment]
Oh, I see. In that case, a clickable link to that section of the log, e.g. https://github.com/eclipse-aspectj/aspectj/actions/runs/8175351748/job/22352264016#step:13:1, would be helpful.

**Comment by cunla** [comment]
That's a nice idea - I am not sure whether the consoleview understands url, but if it does, it is worthwhile doing it.

**Comment by kriegaex** [comment]
@cunla, in 1.18 I now see this in my logs:

> Log is too large to display, open in browser to see full log: https://github.com/eclipse-aspectj/aspectj/actions/runs/8262393796/job/22601614788?#step:13

The thing is, `step:13` just opens the build page, not step 13. That is why I had suggested `step:13:1`, because that does the trick and actually opens the build step, jumping to its first line. Otherwise, the user needs to count steps and open the corresponding one manually. You might want to change that detail for the next release. Thank you.
