### ISSUE TITLE
Realtime view of output

### ISSUE THREAD

**Issue by RichardTMiles** [cunla/ghactions-manager#42]
Howdy howdy!

**Is your feature request related to a problem? Please describe.**
I would love to request a real-time view, and instant update to with every event, not just when a workflow is completed.

<img width="780" alt="Screen Shot 2022-10-04 at 10 21 36 PM" src="https://user-images.githubusercontent.com/9538357/193974132-1e700b56-06c7-473d-8be4-1ce56ca1e940.png">

It is possible to see real-time updates on the browser, maybe here? I'd even open a ticket request for you with Github support if it is a limitation from them.

**Describe the solution you'd like**
A `tail -f` follow along the workflow solution.

**Describe alternatives you've considered**
Setting an auto refresh timer so I don't have to continually click refresh myself!
Refreshing the log API every 60sec..
A link to the that current running workflow.

**Additional context**
Thanks in advance :)

**Comment by cunla** [comment]
Unfortunately, github does not provide an API for that.
