### ISSUE TITLE
Causes hard lockup of Pycharm 

### ISSUE THREAD

**Issue by danros** [cunla/ghactions-manager#55]
**Describe the bug**

Hard lockup of pycharm caused as soon as plugin is used in any way.

PyCharm 2022.2.3 (Professional Edition)
Build #PY-222.4345.23, built on October 10, 2022

Plugin version: 1.5.1

**Comment by cunla** [comment]
Which version of the plugin are you using? I am aware of the issue but trying pinpoint so I won't release trials.

**Comment by cunla** [comment]
I released 1.5.3, which should solve it - it should be published today/tomorrow.
Please inform me if this comes back.

**Comment by danros** [comment]
Unfortunately, I'm seeing the same with 1.5.3, although less frequent.

**Comment by cunla** [comment]
The same lockup?
How many repos do you have in the project?

**Comment by danros** [comment]
Just one, although I used to have two. One remote is now shown in my github options.

**Comment by cunla** [comment]
Can you replicate in the latest version?

**Comment by cunla** [comment]
Hi, any updates on this? does it reproduce on the latest version?

**Comment by cunla** [comment]
I am closing this, please let me know if this happens with the latest version and supply me with whatever information you can to help me investigate
