### ISSUE TITLE
Tab settings don't apply immediately

### ISSUE THREAD

**Issue by moomoohk** [cunla/ghactions-manager#69]
**Describe the bug**
Changes to tab settings (name/visibility/etc) don't appear immediately. In order for them to show, Pycharm must be closed and reopened.

**Steps to reproduce:** 

1. Change tab settings
2. Save settings

**Expected behavior:**
New tab names should be shown, hidden tabs should be hidden.

**Comment by cunla** [comment]
I am not able to replicate this on v1.7.1 - Updating settings seems to apply immediately.

**Comment by moomoohk** [comment]
Updated to v1.7.0 (latest on marketplace as of writing) and everything appears to work fine.
Thanks.
