### ISSUE TITLE
Detect GitHub in remote pushurl as well as url

### ISSUE THREAD

**Issue by pboling** [cunla/ghactions-manager#76]
**Describe the bug**
I have some projects which I push to multiple source forges, github being one of several.  Depending on how I configure it this plugin will either see, or not see, the GitHub config,  I expect it would only require a small change to update the plugin to be compatible with a more ["distributed"](https://railsbling.com/posts/dvcs/) setup.

**Describe the bug:**
GH Actions Manager works ✅ with this config (which I cut for brevity):
```
$ cat .git/config
[remote "origin"]
        url = git@gitlab.com:rubocop-lts/rubocop-ruby3_1.git    # <===== GITLAB
        fetch = +refs/heads/*:refs/remotes/origin/*
...
[remote "all"]
        url = git@github.com:rubocop-lts/rubocop-ruby3_1.git    # <===== GITHUB (WORKS)
        fetch = +refs/heads/*:refs/remotes/all/*
        pushurl = git@gitlab.com:rubocop-lts/rubocop-ruby3_1.git    # <===== GITLAB
        pushurl = git@github.com:rubocop-lts/rubocop-ruby3_1.git    # <===== GITHUB
```
I can see my workflows!

GH Actions Manager does not work ❌ with this config (which I cut for brevity):
```
[remote "origin"]
        url = git@gitlab.com:rubocop-lts/rubocop-ruby3_0.git    # <===== GITLAB
        fetch = +refs/heads/*:refs/remotes/origin/*
[remote "all"]
        url = git@gitlab.com:rubocop-lts/rubocop-ruby3_0.git    # <===== GITLAB
        fetch = +refs/heads/*:refs/remotes/all/*
        pushurl = git@github.com:rubocop-lts/rubocop-ruby3_0.git    # <===== GITLAB
        pushurl = git@gitlab.com:rubocop-lts/rubocop-ruby3_0.git    # <===== GITHUB (DOES NOT WORK)
```
In the plugin pane I see: `No git repositories in project` (an incorrect statement, to be sure)

**Steps to reproduce:** 
Follow the steps here to setup a multi-push remote: https://railsbling.com/posts/dvcs/
For more details, and other related git config commands: https://stackoverflow.com/a/14290145/213191

**Expected behavior:**
Ideally it works if there is a remote `url` **or** `pushurl` for GitHub, but currently it only works when there is a remote `url`.

**Additional context:**

For example, this command could be used to detect presence of GitHub, and it gives the GitHub repo in both of my use cases:

```shell
$ git config -l | egrep '^remote\.all\.(push)?url' | grep 'github'
remote.all.pushurl=git@github.com:rubocop-lts/rubocop-ruby3_0.git
```
and
```shell
$ git config -l | egrep '^remote\.all\.(push)?url' | grep 'github'
remote.all.url=git@github.com:rubocop-lts/rubocop-ruby3_1.git
remote.all.pushurl=git@github.com:rubocop-lts/rubocop-ruby3_1.git
```

Note: I discovered this issue because I failed to follow my own instructions correctly and ended up with different configs... but the config I wanted is the one that currently doesn't work at all, so this was a happy accident.

**Comment by cunla** [comment]
Interesting. I didn't consider the possibility of multiple remotes.
I will get around to it this week.

**Comment by cunla** [comment]
I investigated a bit, the issue here is not multiple remotes but having various pushurls in one remote.
Since I am basing on [jetbrains github plugin](https://github.com/JetBrains/intellij-community/blob/master/plugins/github/src/org/jetbrains/plugins/github/util/GHHostedRepositoriesManager.kt) detection of GitHub repos - I am not able to fix it.
You can open a bug for them perhaps.

**Comment by pboling** [comment]
It should be the case that in the object you are using to access `url` there should be an array of `pushurl`.  If that is not the case, then definitely a JetBrains bug.
