### ISSUE TITLE
outdated workflow status  / jobs

### ISSUE THREAD

**Issue by gberche-orange** [cunla/ghactions-manager#81]
**Describe the bug**

Thanks for the great plugin !

At times, I observe inconsistent outdated list of workflows or jobs

**Describe the bug:**

**Steps to reproduce:** 

* trigger workflow that terminates quickly (such as 15s)

**Expected behavior:**

The github view and plugin view should be in sync

![image](https://user-images.githubusercontent.com/4748380/212763022-1c2d3e2e-e9f2-49c0-b431-06e5d369bf28.png)

in the plugin, some workflow state seem to remain stale: the workflow is marked as still running, while the single job is completed
![image](https://user-images.githubusercontent.com/4748380/212763053-964acb9c-a045-43c8-a188-e6f56bd6a7d2.png)

**Additional context:**

I'm running version 1.9.1

**Comment by cunla** [comment]
Hi, you can configure in the settings how frequently the plugin queries github API. The default is every 30secs.

**Comment by gberche-orange** [comment]
thanks @cunla for looking into this issue. 

* In my environment, lowering the refresh frequency to 5s did not the solve the problem, it even seems more frequent
* Also the workflows remain outdated longer than the refresh frequency

**Comment by gberche-orange** [comment]
thanks a lot @cunla for the fix in release 1.10.0, this is indeed solving the issue I was previously observing !
