### ISSUE TITLE
Step log editor is not properly updated upon theme change

### ISSUE THREAD

**Issue by bric3** [cunla/ghactions-manager#85]
**Describe the bug**
The step logs editor is not properly updated when there's a theme change (eg when the IDE is configured to sync with the OS).
The scrollbars are also not updated properly

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/803621/227273957-54e3b3b9-7d41-4661-9f27-50d247c2eeb8.png">

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/803621/227274170-ab31d604-9ac4-4135-a7f2-759b2d6797ec.png">

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/803621/227274362-eeb96269-5e6f-4cf7-8c67-de9ca534be0b.png">

**Steps to reproduce:** 

1. Open a job
2. Select a step, (log lines should be shown)
3. Switch to a dark or light theme

**Expected behavior:**

Swing tree update should update the editor component.

**Additional context:**

Plugin 1.10.3
macOs 13.2
IntelliJ 2023.1 RC

**Comment by cunla** [comment]
Fixed in 1.11.0
