### ISSUE TITLE
Times are all wrong

### ISSUE THREAD

**Issue by fschoenm** [cunla/ghactions-manager#91]
**Describe the bug**
The time when actions are run are all wrong. It's only 17:16 but the list of action runs says, the run was at 19:14:

![image](https://github.com/cunla/ghactions-manager/assets/687230/cc9ea1ef-a893-4108-9013-57000484a637)
![image](https://github.com/cunla/ghactions-manager/assets/687230/2db71ba7-182e-44dd-ad4e-e0e052163588)
![image](https://github.com/cunla/ghactions-manager/assets/687230/c8b475df-4310-4275-a1a3-9033da5c613e)

I'm on Windows with system clock set to localtime and in time zone CEST/UTC+2 (that might be where the 2 hour offset comes from).

**Comment by cunla** [comment]
Well, it shows the local-time for this.

**Comment by fschoenm** [comment]
No it doesn't. It shows localtime + 2 hours in the screenshots above. 

UTC was 15:15, localtime was 17:15 (CEST/UTC+2), but the display was 19:15 (which was 2 hours in the future; it's actually still in the future right now).

**Comment by karfau** [comment]
I think the fix broke it for linux systems.
I was surprised to see a job has not been run for some hours, but when I check it on github the times are correct.

**Comment by cunla** [comment]
@karfau can you please share a screenshot as well as the json response of https://api.github.com/repos/{OWNER}/{REPO}/actions/runs

**Comment by karfau** [comment]
Sure thing:
```json
{
  "workflow_runs": [
    {
      "created_at": "2023-06-28T23:27:22Z",
      "updated_at": "2023-06-28T23:28:13Z"
    },
    {
      "created_at": "2023-06-28T23:27:22Z",
      "updated_at": "2023-06-28T23:29:30Z"
    },
    {
      "created_at": "2023-06-28T20:33:42Z",
      "updated_at": "2023-06-28T20:38:57Z"
    },
    {
      "created_at": "2023-06-28T20:30:07Z",
      "updated_at": "2023-06-28T20:32:28Z"
    },
    {
      "created_at": "2023-06-28T20:29:08Z",
      "updated_at": "2023-06-28T20:31:19Z"
    },
    {
      "created_at": "2023-06-28T20:08:52Z",
      "updated_at": "2023-06-28T20:11:28Z"
    }
  ]
}
```
I assume that's all the fields you need from that response, if you need more let me know
![image](https://github.com/cunla/ghactions-manager/assets/135657/61d9ac6b-48f7-412c-8062-16274277b5cd)
so it looks like it is showing the exact times that are returned by the API, which I assume are UTC
But in the browser they are converted to my local time:
![image](https://github.com/cunla/ghactions-manager/assets/135657/e69845c9-511a-4f66-a94b-a886021452d5)

**Comment by cunla** [comment]
Ok, this should be fixed in 1.13.1

**Comment by karfau** [comment]
I found this issue by checking the release notes after updating to that version. For me it worked as expected before that version

**Comment by karfau** [comment]
Sorry, I confused 1.12.1 with the version number you mentioned.
For some reason those new versions >=1.13 are not visible on the plugin homepage yet:
https://plugins.jetbrains.com/plugin/19347-github-actions-manager/versions
maybe something in 1.13 broke the compatibility with the current versions of the IDEs?

**Comment by danielm-cfa** [comment]
It takes a few days for jetbrains to approve them.
If you don't want to wait, you can download the release from github.

**Comment by cunla** [comment]
It takes a few days for JetBrains to approve.
If you don't want to wait, you can download it from github and install manually.
