### ISSUE TITLE
Causing GitHub Rate Limit

### ISSUE THREAD

**Issue by jeff-miller-cfa** [cunla/ghactions-manager#94]
I have been dealing with rate limits with GitHub. I would create new tokens and invalidate old ones and yet would still have my user rate limited. By calling <https://api.github.com/rate_limit> I could tell that something in IntelliJ was hitting some GitHub API pretty consistently. After disabling various plugins the requests stopped. I then started re-enabling plugins and found that this was the plugin causing the repeated requests. The ironic thing is that I haven't even open the tool windows so the requests are completely unnecessary. 

This becomes an even bigger problem when you have multiple IntelliJ windows open. I regularly will have 10+ projects open. And our projects have ~15 workflows. So I am guessing all the requests are because this plugin is polling logs for each workflow for each project which would be 150 requests ever 30 seconds. At this frequency I will cross the 5000 request rate limit in about 15 minutes.

Would it be possible to update this plugin to only poll if the tool windows are active? If not I'm going to have to leave this plugin disabled.

**Comment by cunla** [comment]
The requests this plugin makes:
- refresh workflow runs
- refresh branches
- refresh collaborators

Every 30s by default (this can be changed)

Additionally, when a workflow-run is selected (and only then) - it makes a request to get the log and a request to get the jobs.

Also, it only makes the requests on the selected repository.

So, for 15 projects, assuming you constantly select different workflow runs and don't change the 30s frequency, you will reach 5000 requests in 8h.

**Comment by danielm-cfa** [comment]
issue is caused due to pagination of /collaborators requests.

potential fixes:
=> make /collaborators request once without refresh.
=> increase page size in /collaborators request.

**Comment by cunla** [comment]
Fixed in 1.13.3
